apiVersion: v1
data:
    password: ENC[AES256_GCM,data:j6rQ+7WzyBo=,iv:ISnvaGZQYJUvERcCxFtdBZ4KqTvoKL7J/f755Iib4io=,tag:OPUoe5QCBbpsPZFFitD51g==,type:str]
    user: ENC[AES256_GCM,data:OKYcFRamQLI=,iv:r+3ac/6kMbDa0QLLbrMwXQYwJaBwNHDAL1FkbSyEcSM=,tag:tEkwXJSykwGOo+Y1PsQsgA==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV3lpRWdyTkZyWnZCUzlP
            L3djQ0FCRmNKU1M4R1VJZFg4U1l3TkNGOHhnCjFmN250bzF2dHJ4ck1kdGtOMnN3
            amVXR2Z5ZW5qSit0ZFg5dXhzMGQ5VVUKLS0tIHFoa3hrUDRWVkhVcHJRSXZRTm95
            YndIZzFPelBMeFJ4S3c0a2NxdXFZNjgKe7EOWZN4I1yA3pfjtE9Y4yjEY5E+23B0
            pLzPZJvP5EgBVJYa7In7Xay9qn3717bZWsgViUCKKAYQ+fsZTCVUZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r6h24df7s5g38yvm2ytwtfev4zqhv8wvglrypugfqxf8s30yvqcqsektlj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T23:16:17Z"
    mac: ENC[AES256_GCM,data:2QnqKbeim1xWSAu3WIAXdhIobnBw/ELZYTMgRLHjJpMB85S4OwcPEVS8zEuOHLO8CePJz5fn0Ta+3aUll4v9sv2BzOGB/Tik7XbxcX0kRKA1a4KtAjM3oco1gHtd9DO1h0fwGk5+o8ao99Aidmr9Hqkf3t0Dj7UziAi3nOyg35A=,iv:ReAq3fAVTbIGzFXM7DB9AVMCN6nmIt3ToDL98S/0Nhs=,tag:YAhpV2LzM2sg8SAmpyd44A==,type:str]
    version: 3.13.3
